version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: unless-stopped
    volumes:
      - data:/data/db
  redis:
    image: redis
    ports:
      - '6380:6380'
    restart: unless-stopped
    volumes:
      - redisdata:/data
  api:
    build: .
    # volumes:
    #   - .:/usr/src/app
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  data:
  redisdata:
