name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache clean
        run: npm cache clean --force

      - name: Delete node modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build and package application
        run: npm run build

      - name: Deploy to production
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            npm run prod
          else
            echo "Skipping production deployment for branch other than main"
          fi
